package Controlador;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;
import Aplicacion.Main;
import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

public class ListaExamenesController {
	@FXML
	private TextField txtNombreAlumno;
	@FXML
	private ComboBox<?> comboBoxNombresExamenes;

	// Event Listener on Button.onAction
	@FXML
	public void Responder(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void Salir(ActionEvent event) {
		// TODO Autogenerated
	}
	public void setMainApp(Main main, String correo) {
		
	}
}
