package Controlador;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;
import BD.Conexion;
import javafx.event.ActionEvent;

import javafx.scene.control.SplitMenuButton;

import javafx.scene.control.PasswordField;

public class LoginController {

	Conexion conexion = new Conexion();

	@FXML
	private TextField txtEmail;
	@FXML
	private PasswordField txtPassword;
	@FXML
	private SplitMenuButton splitRol;

	// Event Listener on Button.onAction
	@FXML
	public void ingresar(ActionEvent event) {
		String textoEmail = this.txtEmail.getText();
		String textoContrasena = this.txtPassword.getText();

		System.out.println("el usuario "+textoEmail+" hizo la consulta:");
		System.out.println();
		conexion.realizarConsulta("select nombre from alumno");
	}
	// Event Listener on Button.onAction
	@FXML
	public void volver(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void cambiarRolEstudiante(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void cambiarRolDocente(ActionEvent event) {
		// TODO Autogenerated
	}
}
