package Controlador;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.SplitMenuButton;

import javafx.scene.control.PasswordField;

public class LoginController {
	@FXML
	private TextField txtEmail;
	@FXML
	private PasswordField txtPassword;
	@FXML
	private SplitMenuButton splitRol;

	// Event Listener on Button.onAction
	@FXML
	public void ingresar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void volver(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void cambiarRolEstudiante(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void cambiarRolDocente(ActionEvent event) {
		// TODO Autogenerated
	}
}
