package Controlador;

import javax.swing.JOptionPane;

import Aplicacion.Main;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.PasswordField;
import javafx.scene.control.SplitMenuButton;
import javafx.scene.control.TextField;

public class LoginController {
	private Main aplicacion;
	private String usuario;

	@FXML
	private TextField txtEmail;
	@FXML
	private PasswordField txtPassword;
	@FXML
	private SplitMenuButton splitRol;

	// Event Listener on Button.onAction
	@FXML
	public void ingresar(ActionEvent event) {
		if (camposRellenos()) {
			String correo = txtEmail.getText();
			String password = txtPassword.getText();
			if (this.usuario.equals("alu")) {
				if (aplicacion.ingresarAlumno(correo, password)) {
					aplicacion.showListaExamenes(correo);
				} else {
					JOptionPane.showMessageDialog(null, "Alumno no encontrado o contraseña invalida");
				}
			}
			if (this.usuario.equals("doc")) {
				if (aplicacion.ingresarDocente(correo, password)) {
					aplicacion.showCrearExamen(correo);
				} else {
					JOptionPane.showMessageDialog(null, "Docente no encontrado o contraseña invalida");
				}
			}
			if (this.usuario.equals("adm")) {
				if (aplicacion.ingresarAdmin(correo, password)) {
					aplicacion.showCrearExamen(correo);
				} else {
					JOptionPane.showMessageDialog(null, "Administrador no encontrado o contrase�a invalida");
				}
			}
		}else{
			JOptionPane.showMessageDialog(null, "Rellene todos los campos y elija un rol");
		}
			
	}

	// Event Listener on Button.onAction
	@FXML
	public void volver(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on MenuItem.onAction
	@FXML
	public void cambiarRolEstudiante(ActionEvent event) {
		splitRol.setText("Alumno");
    	this.usuario = "alu";
	}

	// Event Listener on MenuItem.onAction
	@FXML
	public void cambiarRolDocente(ActionEvent event) {
		splitRol.setText("Docente");
    	this.usuario = "doc";
	}
	// Event Listener on MenuItem.onAction
	@FXML
	void cambiarRolAdministrador(ActionEvent event) {
		splitRol.setText("Administrador");
    	this.usuario = "adm";
	}

	private boolean camposRellenos() {
		if (txtEmail.getText().isEmpty()) {
			return false;
		}
		if (txtPassword.getText().isEmpty()) {
			return false;
		}
		if (splitRol.equals("Seleccione un rol") || this.usuario == null) {
			return false;
		}
		return true;
	}
	
	@FXML
    void initialize() {

    }
	
	public void setMainApp(Main aplicacion) {
		this.aplicacion = aplicacion;
	}
}
