package Controlador;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class ModuleChoiceController {
	@FXML
	private Label lblBienvenido;
	@FXML
	private Label lblUsuarioIngresado;
	@FXML
	private Label lblRolUsuarioIngresado;

	// Event Listener on Button.onAction
	@FXML
	public void ingresar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void registro(ActionEvent event) {
		// TODO Autogenerated
	}
}
