package Controlador;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.RadioButton;

public class RespuestaExamenController {
	@FXML
	private RadioButton opcionAPre1;
	@FXML
	private TextField txtNombreExamen;
	@FXML
	private TextField txtPregunta1;
	@FXML
	private RadioButton opcionBPre1;
	@FXML
	private RadioButton opcionCPre1;
	@FXML
	private RadioButton opcionAPre2;
	@FXML
	private TextField txtPregunta2;
	@FXML
	private RadioButton opcionBPre2;
	@FXML
	private RadioButton opcionCPre2;
	@FXML
	private RadioButton RbVerdaderoPre3;
	@FXML
	private TextField txtPregunta3;
	@FXML
	private RadioButton RbFalsoPre3;
	@FXML
	private RadioButton RbVerdaderoPre4;
	@FXML
	private TextField txtPregunta4;
	@FXML
	private RadioButton RbFalsoPre4;

	// Event Listener on Button.onAction
	@FXML
	public void Enviar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void Salir(ActionEvent event) {
		// TODO Autogenerated
	}
}
